x-postgres-common: &postgres-common
  build: ./compose-configuration/postgres
  cpus: "1.0"
  mem_limit: 1g
  networks:
    - postgres
  depends_on:
    etcd:
      condition: service_healthy

x-postgres-environment: &postgres-environment
  POSTGRES_DB: ${SOCIAL_NETWORK_DB_NAME}
  POSTGRES_USER: ${SOCIAL_NETWORK_DB_USERNAME}
  POSTGRES_PASSWORD: ${SOCIAL_NETWORK_DB_PASSWORD}
  POSTGRES_REPLICATION_USER: ${REPLICATION_USER}
  POSTGRES_REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
  ETCD_NAME: etcd

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.26
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: default=http://etcd:2380

    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health", "--endpoints=http://etcd:2379" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - postgres

  postgres-1:
    <<: *postgres-common
    environment:
      <<: *postgres-environment
      PATRONI_NAME: postgres-1
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://postgres-1:8008/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-2:
    <<: *postgres-common
    environment:
      <<: *postgres-environment
      PATRONI_NAME: postgres-2
    volumes:
      - postgres_2_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://postgres-2:8008/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-3:
    <<: *postgres-common
    environment:
      <<: *postgres-environment
      PATRONI_NAME: postgres-3
    volumes:
      - postgres_3_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://postgres-3:8008/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  haproxy:
    build: ./compose-configuration/haproxy

    depends_on:
      postgres-1:
        condition: service_healthy
      postgres-2:
        condition: service_healthy
      postgres-3:
        condition: service_healthy

    networks:
      - postgres
      - social_network

    volumes:
      - ./compose-configuration/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

    healthcheck:
      test: [ "CMD-SHELL", "nc -z haproxy 5432 && nc -z haproxy 5433" ]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"
      - "5433:5433"

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      SOCIAL_NETWORK_READ_DB_URL: ${SOCIAL_NETWORK_READ_DB_URL}
      SOCIAL_NETWORK_WRITE_DB_URL: ${SOCIAL_NETWORK_WRITE_DB_URL}
      SOCIAL_NETWORK_DB_USERNAME: ${SOCIAL_NETWORK_DB_USERNAME}
      SOCIAL_NETWORK_DB_PASSWORD: ${SOCIAL_NETWORK_DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}

    depends_on:
      haproxy:
        condition: service_healthy

    networks:
      - social_network

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://backend:8080/api/health-check/ping || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  postgres_2_data:
  postgres_3_data:

networks:
  postgres:
  social_network:
