spring.application.name=social-network

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.datasource.read.url=${SOCIAL_NETWORK_READ_DB_URL}
spring.datasource.read.username=${SOCIAL_NETWORK_READ_DB_USERNAME}
spring.datasource.read.password=${SOCIAL_NETWORK_READ_DB_PASSWORD}
spring.datasource.read.hikari.maximum-pool-size=20

spring.datasource.write.url=${SOCIAL_NETWORK_WRITE_DB_URL}
spring.datasource.write.username=${SOCIAL_NETWORK_WRITE_DB_USERNAME}
spring.datasource.write.password=${SOCIAL_NETWORK_WRITE_DB_PASSWORD}
spring.datasource.write.hikari.maximum-pool-size=20

jwt.secret=${JWT_SECRET}
jwt.access-token-ttl=${JWT_ACCESS_TOKEN_TTL}

social-network.import.batch-size=${SOCIAL_NETWORK_IMPORT_BATCH_SIZE:10000}
