spring.application.name=social-network

spring.datasource.url=${SOCIAL_NETWORK_DB_URL}
spring.datasource.username=${SOCIAL_NETWORK_DB_USERNAME}
spring.datasource.password=${SOCIAL_NETWORK_DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.access-token-ttl=${JWT_ACCESS_TOKEN_TTL}
